-- MySQL Script generated by MySQL Workbench
-- 09/19/18 22:19:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogspock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogspock` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema blogspock
-- -----------------------------------------------------

-- -----------------------------------------------------
USE `blogspock` ;

-- -----------------------------------------------------
-- Table `blogspock`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogspock`.`acesso` (
  `idAcesso` INT NOT NULL COMMENT '',
  `nivel` VARCHAR(45) NULL COMMENT '',
  `gerPost` TINYINT NULL COMMENT '',
  `gerComent` TINYINT NULL COMMENT '',
  `gerBlog` TINYINT NULL COMMENT '',
  `gerUsuario` TINYINT NULL COMMENT '',
  PRIMARY KEY (`idAcesso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogspock`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogspock`.`usuario` (
  `idusuario` INT NOT NULL COMMENT '',
  `nome` VARCHAR(50) NULL COMMENT '',
  `data_nasci` DATE NULL COMMENT '',
  `senha` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(70) NULL COMMENT '',
  `dataRegistro` DATE NULL COMMENT '',
  `acesso_idAcesso` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idusuario`, `acesso_idAcesso`)  COMMENT '',
  INDEX `fk_usuario_acesso_idx` (`acesso_idAcesso` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_acesso`
    FOREIGN KEY (`acesso_idAcesso`)
    REFERENCES `blogspock`.`acesso` (`idAcesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogspock`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogspock`.`post` (
  `idpost` INT NOT NULL COMMENT '',
  `removed` TINYINT NULL COMMENT '',
  `titulo` VARCHAR(30) NULL COMMENT '',
  `descricao` VARCHAR(50) NULL COMMENT '',
  `textoPost` TEXT NULL COMMENT '',
  `ult_Alt` DATETIME NULL COMMENT '',
  `horaCriacao` DATETIME NULL COMMENT '',
  `usuario_idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idpost`, `usuario_idusuario`)  COMMENT '',
  INDEX `fk_post_usuario1_idx` (`usuario_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `blogspock`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogspock`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogspock`.`comentario` (
  `idcomentario` INT NOT NULL COMMENT '',
  `coment` TEXT NULL COMMENT '',
  `horaCriacao` DATE NULL COMMENT '',
  `comentario_idcomentario` INT NOT NULL COMMENT '',
  `post_idpost` INT NOT NULL COMMENT '',
  `usuario_idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcomentario`, `usuario_idusuario`)  COMMENT '',
  INDEX `fk_comentario_comentario1_idx` (`comentario_idcomentario` ASC)  COMMENT '',
  INDEX `fk_comentario_post1_idx` (`post_idpost` ASC)  COMMENT '',
  INDEX `fk_comentario_usuario1_idx` (`usuario_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_comentario_comentario1`
    FOREIGN KEY (`comentario_idcomentario`)
    REFERENCES `blogspock`.`comentario` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `blogspock`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `blogspock`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogspock`.`blog_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogspock`.`blog_options` (
  `idBlogOpt` INT NOT NULL COMMENT '',
  `opt_name` VARCHAR(45) NULL COMMENT '',
  `opt_value` VARCHAR(50) NULL COMMENT '',
  `usuario_idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idBlogOpt`, `usuario_idusuario`)  COMMENT '',
  INDEX `fk_blog_options_usuario1_idx` (`usuario_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_blog_options_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `blogspock`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
